### ISSUE TITLE
Invalid Proposal Signature when using Multiple Outputs

### ISSUE THREAD

**Issue by bitalias** [bitpay/bitcore-wallet-client#116]
Hi,

tried to fix the bug myself, but I keep getting 
```js
 { code: 'BADREQUEST', message: 'Invalid proposal signature' } 
```
as a response when I use the multiple output syntax for sending a tx proposal (https://github.com/bitpay/bitcore-wallet-client#API#sendTxProposal), even if the ops.outputs list contains only one output. 

Samples:
```js
{ toAddress: undefined,
  amount: undefined,
  message: null,
  feePerKb: undefined,
  payProUrl: undefined,
  excludeUnconfirmedUtxos: false,
  type: undefined,
  outputs: 
   [ { toAddress: 'mtVwSwnWwJgJMdMFG6XqWFESd5uBqB5Czt',
       amount: 31674,
       message: '{"iv":"uvQsaY97XwuMIzpBINC19A==","v":1,"iter":1,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","ct":"XdRV7AA17IMd54O5LoYKJem+"}' } ],
  proposalSignature: '30450221008657ac887421e69f72cbbd1d703c827114efbe985edd3873caebbe629b8ad323022040f8eb4a4818f8c053a47c7613cfa5e35d6e69ca043728e55eec1cbda3891a91' }
```

```js
{ toAddress: undefined,
  amount: undefined,
  message: null,
  feePerKb: undefined,
  payProUrl: undefined,
  excludeUnconfirmedUtxos: false,
  type: undefined,
  outputs: 
   [ { toAddress: 'muGzYjfhWahnaJa1K56nKxxSEkFtVP4yHx',
       amount: 10816,
       message: '{"iv":"er0p3jZon3K19zjOGkPIOg==","v":1,"iter":1,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","ct":"M/y+rZ1IIUWvHoy3gHLLkMw="}' },
     { toAddress: 'mwGVtd7aHBnyAnqhJS1iBQwzCHAvGZHpAF',
       amount: 52576,
       message: '{"iv":"lkhSkUiP13emLjGHyi0W0w==","v":1,"iter":1,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","ct":"XcehZzAPxy6CINCYA8qn4XY="}' },
     { toAddress: 'n1pCcYPBvcbEj26eh8k2zL4QCn5CgsK4iK',
       amount: 4348,
       message: '{"iv":"yEz+VzfBvQzb7SMDPTN95g==","v":1,"iter":1,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","ct":"9xbp9W8PsEt4nMoDC/m2fJE="}' } ],
  proposalSignature: '30440220262b8c150534a99390b024d3608506ff1dcea0eed734483491205e864bedcfa2022063ff188550d56bf3cc104a3cf70f683622380348e1a3ecb9a0861f223ae73a96' }
```

All works fine when using the single output syntax.

Using the bitcore wallet service by Bitpay - where I think the bug is.

Hope that somebody can help!

Thanks!

P.S.: What also could be improved that all those 'undefined' values do not appear. A bit confusing.

**Comment by greggzigler** [comment]
hi @bitalias , can you tell me which version of bitcore-wallet-client you are using? Also, can you confirm that you are use https://bws.bitpay.com/bws/api ?

**Comment by bitalias** [comment]
Of course!

BWS_INSTANCE_URL: 'https://bws.bitpay.com/bws/api'
bitcore-wallet-client "version": "0.1.3"

matiu pointed that I might need to run the latest version of BWS. Bitpay does not host it?

**Comment by matiu** [comment]
yes, bitpay runs the latests version.

On Thu, Aug 20, 2015 at 11:13 AM, bitalias <notifications@github.com> wrote:

> Of course!
>
> BWS_INSTANCE_URL: 'https://bws.bitpay.com/bws/api'
> bitcore-wallet-client "version": "0.1.3"
>
> matiu pointed that I might need to run the latest version of BWS. Bitpay
> does not host it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-wallet-client/issues/116#issuecomment-133025084>
> .
>



-- 
BitPay.com

**Comment by greggzigler** [comment]
i just tested 0.1.3 with bws.bitpay.com, and it worked for me. here is the ops that i sent to the server:

{ type: 'multiple_outputs',
  message: 'test proposal multiple_outputs production',
  payProUrl: 'https://merchant.com/pay.php?h%3D2a8628fc2fbe',
  outputs: 
   [ { amount: 603,
       toAddress: '2Mvy31zP2Sy9YEUDz3sc2kPvK5FgnpAS1VA',
       message: 'output #1' },
     { amount: 602,
       toAddress: '2N43GneRXWQ1W1gh8sGts2zNQjsW7ZdGtLi',
       message: 'output #2' },
     { amount: 601,
       toAddress: '2N7feLUhQ4La4JxgbNpYZyw8KHBWveA8dWC',
       message: 'output #3' } ] }

One thing I notice from your sample data above is that 'type' is undefined. Try writing 'multiple_outputs' there and see if it works.

**Comment by bitalias** [comment]
@greggzigler Thanks a lot! Documentation was indeed incomplete. Works now! But could definitely be also implicit without declaration.

**Comment by ayush-techracers** [comment]
Hi @greggzigler, 
I am creating usdt multisig transaction using bitcore-wallet-client. So when I am adding the opreturn output then its throwing me the error ` { code: 'BADREQUEST', message: 'Invalid proposal signature' } `
Could you please provide a little details over the solution that you have shared. Since I have tried to add the type but it didn't work. So could you please suggest where shall I add the type? Also is this required to add the paypro url ? 
And would the paypro url be different for testnet and livenet?
Also I am using using ` "bitcore-wallet-client": "^6.4.0"` and url is https://bws.bitpay.com/bws/api.

**Comment by greggzigler** [comment]
Hi @ayush-techracers, it looks my three-year-old code change has been improved. For a likely up-to-date solution, I suggest looking at the unit test at https://github.com/bitpay/bitcore-wallet-client/blob/master/test/client.js#L862 <https://github.com/bitpay/bitcore-wallet-client/blob/master/test/client.js#L862>.
