### ISSUE TITLE
dryRun in 0.4.1 release

### ISSUE THREAD

**Issue by DavidApfel** [bitpay/bitcore-wallet-client#141]
It seems the new "joinWallet dryRun" option is not enabled in 0.4.1 release. Which release does have it? Thanks

**Comment by isocolsky** [comment]
That feature should be in 0.6.0 release.

**Comment by DavidApfel** [comment]
Could you tell me when it's going to be released more or less? Thank you.

**Comment by matiu** [comment]
Done,sorry, we forgot to tag the release in github.  Just for curiosity, are you using bitcore-wallet-client thru bower?

**Comment by DavidApfel** [comment]
No, I'm not using it thru bower.
