### ISSUE TITLE
Make all errors actual JavaScript Errors

### ISSUE THREAD

**Issue by gabegattis** [bitpay/bitcore-wallet-client#183]
In BWC, not all errors are actual JS Error objects. See https://github.com/bitpay/bitcore-wallet-client/tree/master/lib/errors

This can make code that uses BWC  somewhat ugly and odd. Some functions have to handle errors one way, and others a different way.

Bitcore has a good way of dealing with custom errors. See https://github.com/bitpay/bitcore-lib/tree/master/lib/errors

**Comment by braydonf** [comment]
This was added in: https://github.com/bitpay/bitcore-wallet-client/pull/189
