### ISSUE TITLE
Is there any more thorough documentation?

### ISSUE THREAD

**Issue by wzrdtales** [bitpay/bitcore-wallet-client#227]
The current docs in the README are not only outdated, but there are also many information missing.

What exactly should be isComplete be for? What should this check for being complete? For the wallet to be completely open or...

If there are detailed docs, papers about the concepts anything I would be greatful. Thanks

**Comment by matiu** [comment]
`isComplete` mean is the wallet is complete (all copayers have joined) or if it still waiting for other copayers to join.

You should check it after `openWallet`.  

There is no extra documentation, you can check `bitcore-wallet` for a simple CLI client that use BWC. (https://github.com/bitpay/bitcore-wallet)

**Comment by wzrdtales** [comment]
@matiu Thanks, also that this was just an example. Please insert this information in the docs, it will also help others...

I have looked into all of this, I also need to look into copay to see how some things are handeled...
I hope you're going to start with the documentation soon, currently this is a really big chaos across all projects concerning bws including bws itself..., not only related to documentation though. No information to start through contributing, missing tags on github of the npm releases (I had to get the gitHead from npm instead for bws for example).

Really please start organizing all of this a bit more, you're wasting so much potential through the community that would contribute that you're loosing completely. I'm sorry, but I have to admit that it is currently really not funny to gather all information to use your stuff, because there is either no or completely outdated documentation... . And also please stop closing issues without the chance to communicate, this is ultimately rude... I have noticed that many times now in all bitpay projects that this happens in this style though and that is not going to make people to be more into asking questions it is more like saying:
"Hey go away, we don't want you here. It is our project,"

Also to mention, this is no offense and was not ment to offend, this was ment as criticism.

**Comment by matiu** [comment]
Thanks a lot for you comment. We will definitely will try to tag the releases better and maintain npm updated. Also we will work to have the README docs updated, to start.

Please if your proyect is OSS, let us know so we can link it
