### ISSUE TITLE
Wrong decimals definition for bits

### ISSUE THREAD

**Issue by trapp** [bitpay/bitcore-wallet-client#239]
lib/common/constants.js defines for the unit bit:

```js
bit: {
    toSatoshis: 100,
    maxDecimals: 0,
    minDecimals: 0,
},
```

This leads to rounding in Copay and falsifies amounts shown (it even rounds up sometimes). See issue bitpay/copay#4004 for example.

Why is the unit bit defined like this?

Wouldn't setting it to `maxDecimals: 2` and `minDecimals: 2` lead to a more intuitive ui?

**Comment by matiu** [comment]
Related / Dup: https://github.com/bitpay/copay/issues/3125
