### ISSUE TITLE
Import of Copay exported wallet doesnt follow docs

### ISSUE THREAD

**Issue by ziggamon** [bitpay/bitcore-wallet-client#261]
API.prototype.import states that it should take an opts object with a password param. This does not work in the code.

Instead after some time playing around, here's code for importing a Copay exported wallet:

```
var fs = require('fs');
var sjcl = require('sjcl');

var walletFile = './your-wallet.aes.json';
var password = 'your-password';

var walletData = fs.readFileSync(require('path').resolve(__dirname, walletFile), 'utf-8');
var decrypted = sjcl.decrypt(password, walletData);
client.import(decrypted);
```

Please update docs or even better update the import function to support encryption. Esp as the Copay wallet does not allow unencrypted exports.

**Comment by matiu** [comment]
Thanks for the code snipped, would you mind adding a section in the Readme with that code? I think that many people may find that useful, since this seems to be a common use case.

I dont think that decrypting the backup is a responsibility of BWC, but I do agree of adding this to the doc.

thanks a lot!

**Comment by ziggamon** [comment]
Well the documentation refers to decryption capabilities that aren't there. And currently 'sjcl' isn't exposed (what I could find) from BWC.

But most important reason IMO: Since Copay is the defacto GUI for bitcore suite, and Copay only exports in encrypted format the code should IMO be able to import it. It's not much code, could probably be fit into that function, but I'm afraid to modify it as I don't fully understand what it does and am relatively new with Bitcore, not feeling ready to "contribute" yet.
