### ISSUE TITLE
How to open 1-1 wallet created by bitcore-wallet

### ISSUE THREAD

**Issue by igorvlassov** [bitpay/bitcore-wallet-client#272]
Hello,
I have created 1-1 wallet with wallet-create bitcore-wallet command. It does not shows shared key in that case. How could I open that wallet with bitcore-wallet-client API?

Thanks in advance,
Igor

**Comment by dabura667** [comment]
When did you make the wallet? Is the wallet type P2SH or P2PKH?

**Comment by igorvlassov** [comment]
Well, I have managed to open it with sequence:

 client.seedFromExtendedPrivateKey(xPrivKey);
 client.openWallet(function(err, ret) 

but not sure is that a best way to do this.

**Comment by dabura667** [comment]
I put spaces in there to show you where I have JSON.parse()...
I will explain after the code sample.

```javascript
var Client = require('bitcore-wallet-client');


var fs = require('fs');
var BWS_INSTANCE_URL = 'https://bws.bitpay.com/bws/api'

var client = new Client({
  baseUrl: BWS_INSTANCE_URL,
  verbose: false,
});
client.import(   JSON.parse(   fs.readFileSync('abc.dat').toString()   )   )
```

Older versions of BW saved files with quotes in them, so:

```javascript
"{\"name\":\"blahblah\",\"m\":1.......}" // etc
```

Newer versions store the object directly in the file without quotes...
```javascript
{"name":"blahblah","m":1.......} // etc
```

If you have the newer ones you can use

**Comment by igorvlassov** [comment]
@dabura667  thanks a lot, I'll check tomorrow and let you to know.

**Comment by igorvlassov** [comment]
Looks like JSON.parse does not work for me. When I tried to address some JSON element, I get undefined:
var walletContent = JSON.parse(fs.readFileSync('.wallet.dat').toString());
process.stdout.write(walletContent+'\n'); // Shows something like {"network":"testnet","xPrivKey":"tprv...", etc.
But  
process.stdout.write(walletContent.xPrivKey+'\n'); 
shows undefined.
I think it's because of quotes on JSON sub-object names.
If I tried to get members from JSON like { version: '1.0.0',
  createdOn: 1464161716,
  address: 'mo...', etc, all OK for me

**Comment by dabura667** [comment]
No, you need to do one more JSON.parse()

In my example, I do JSON.parse one time, but client.import() also does JSON.parse one more time (which is why I only do it once)

**Comment by igorvlassov** [comment]
@dabura667 I found where I was wrong. I tried to open wallet after import with client.openWallet(function(err, ret)...
and got undefined values for expected ret fields.
As I see wallet is already opened after import and I can go to the next steps.
Thanks a lot!
