### ISSUE TITLE
Create wallet using node keys?

### ISSUE THREAD

**Issue by igorvlassov** [bitpay/bitcore-wallet-client#275]
Hello,

I try to develop service that allows to create wallets.
I have started full test node using bitcore, etc.

Now when I try to create wallet from code like in the example there it looks OK:

```
var Bitcore = require('bitcore-lib');
var Client = require('bitcore-wallet-client');

var fs = require('fs');
var BWS_INSTANCE_URL = 'http://localhost:3232/bws/api'

var client = new Client({
  baseUrl: BWS_INSTANCE_URL,
    verbose: false,
    });

client.createWallet("Irene2", "Irene2", 1, 1, {network: 'testnet'}, function(err, secret) 
{
  if (err) 
  {
      console.log('error: ',err); 
      return
    };
    // Handle err
    fs.writeFileSync('/Users/aaa/irene2.dat', client.export());
});

```
Wallet is created.
But when I try to open it by code:
`client.import(JSON.parse(fs.readFileSync('/Users/aaa/irene2.dat').toString()));`
I get INVALID_BACKUP error.

As I could assume this is because of random keys usage in the first example. I think I need to derive new keys for new wallet from main node key. 
Could you point me how to get access to it?

Thanks,
Igor

**Comment by isocolsky** [comment]
Try importing it using:
```client.import(fs.readFileSync('/Users/aaa/irene2.dat').toString());```

BWC will do the JSON.parse() for you.
Hope this helps.

**Comment by igorvlassov** [comment]
@isocolsky WOW it works, thanks a lot!!!

**Comment by Chibuzo** [comment]
@isocolsky is it safe to save wallet file (eg irene.dat) containing the private key on the server? Can't it be easily stolen?

**Comment by isocolsky** [comment]
The .dat file generated by BWC is not encrypted so avoid storing it remotely. That being said, if you called the `encryptPrivateKey()` method and do not pass a `password` argument to the `export()` method, the private key will be encrypted and (as long as your password has enough entropy) your funds will be safe. Keep in mind that this only protects your funds from getting stolen but does nothing to protect your privacy as the public keys are still in the clear.
