### ISSUE TITLE
createTxProposal: max outputs limit?

### ISSUE THREAD

**Issue by igorvlassov** [bitpay/bitcore-wallet-client#289]
Dear Sirs,
I need to implement mass payment system, when TxProposal from one wallet will be sent to multiple wallets. I successfully created transaction with 10 outputs. 
But I wonder now is there maximum outputs limit.
Could you point me please?

Thanks in advance,
Igor

**Comment by dabura667** [comment]
No.

**Comment by dabura667** [comment]
But the bitcoin network will not relay transactions that are over 100 kilobytes large... (actually I think that number has gone down... I would avoid making any transaction larger than 5 kilobytes)

**Comment by igorvlassov** [comment]
Interesting. And how big the ordinary 1-1 transaction, what do you think?

**Comment by igorvlassov** [comment]
Found the formula:
180 bytes per input + 34 bytes per output + 10 bytes

**Comment by dabura667** [comment]
This is a byte size estimation formula I use:

```javascript
var isP2PKH = true; // If false, then is multisig, if true, it is a single sig wallet with address starting with 1.

var inputSize; // size added to transaction for each input added
if(!isP2PKH) {
  var m = 2; // number of sigs required
  var n = 3; // number of participants in the wallet
  inputSize = (73 * m) + (34 * n) + 49; // m multiply by signature bytes, n multiply by pubkey bytes + 49
} else {
  inputSize = 148; // it could also be 147, but I estimate large.
}

var sendingToP2PKH = true; // P2SH multisig address outputs are 32 bytes and normal P2PKH ("1" addresses) are 34 bytes

var outputSize = sendingToP2PKH ? 34 : 32;

var numberOfInputs = 3;
var numberOfOutputs = 2; // Copay will automatically add one output for you automatically for change
// So sending to 3 users will require 4 outputs.

var estimatedByteSize = (numberOfInputs * inputSize) + (numberOfOutputs * outputSize) + 10;
// this is a very good estimate. If it is ever incorrect, it will guess too large by only a few bytes.
```

**Comment by dabura667** [comment]
> 180 bytes per input

That is for old keys. (where the private key starts with a 5 and not a K or L)
Copay, B-W-C, and all HD wallets use newer keys where input size is 148 bytes.

**Comment by dabura667** [comment]
@igorvlassov if your service will have many inputs, you can not send to a lot of users... inputs are much larger...

so give an idea, if you only use 1 input and send to 500 users
17192 bytes

1 inputs and 2935 users
99982 bytes

So assuming you only have 1 or a few inputs, I would say limit your user sends to 100 users at one time.

With 101 outputs (remember you need change) you could include 10 inputs and still be under 5000 bytes.

**Comment by dabura667** [comment]
Copay will automatically calculate your fee.

It will always be more cost effective to include more users in one transaction... in my 2935 user example, that is 34.065 bytes per user send.

If you did one transaction per user it would be 227 bytes per user. each byte is costing you money.

10 input 100 users transaction would be 49.24 bytes per user, which means much savings on fees.

**Comment by igorvlassov** [comment]
@dabura667 Thanks a lot for explanation. The most problematic for me is to wait confirmation between transactions.

**Comment by dabura667** [comment]
You don't need to.

There is a setting in the wallet to allow spending if zero confirms.

As long as you use priority fees, you should be fine.

**Comment by igorvlassov** [comment]
> There is a setting in the wallet to allow spending if zero confirms.
I checked docs but don't find such setting. Could you point me to?
What do "priority fees" mean? Big enough fees? What amount? Is 40000 enough?

**Comment by dabura667** [comment]
The default is to include 0-conf unless you specify otherwise.

Priority fees would mean including a feePerKb polled by insight to match the current network fee rates.

**Comment by dabura667** [comment]
I am not sure what you're trying to do. If you could post source I could look at it for you.

**Comment by dabura667** [comment]
I've confirmed default behavior is to give 0 confirm utxos when asking for getUtxos

```javascript
> client.getUtxos({}, function (err, utxos) {
...   console.dir(err);
...   console.dir(utxos);
... });
undefined
> null
[ { txid: 'dcf5d07ae4c04e78e641f0ca526370770c7ba6c7df98a2e0f9fb42d9bc814681',
    vout: 0,
    address: 'myBSRKpVWtbrEAUKebQFJhPvpu1iP14mhk',
    scriptPubKey: '76a914c1c16c39125638a5b5680bc402b7f4fbd4268fab88ac',
    confirmations: 0,
    locked: false,
    satoshis: 9538600,
    path: 'm/0/1',
    publicKeys: [ '03f876f6e2889561ad5edef77373710db9e5293f9931b77cecb4085ad0bd943478' ] },
  { txid: 'e1124d0a99e2d32b8d6d65e2e38d3589e4c8a9fba474d269cf7d2d3f901eaf59',
    vout: 1,
    address: 'myBSRKpVWtbrEAUKebQFJhPvpu1iP14mhk',
    scriptPubKey: '76a914c1c16c39125638a5b5680bc402b7f4fbd4268fab88ac',
    confirmations: 0,
    locked: false,
    satoshis: 537600,
    path: 'm/0/1',
    publicKeys: [ '03f876f6e2889561ad5edef77373710db9e5293f9931b77cecb4085ad0bd943478' ] } ]
```

**Comment by dabura667** [comment]
@igorvlassov Also, "priority" fees is checked with `getFeeLevels`

```javascript
> client.getFeeLevels('livenet', function(err, res) { // or 'testnet'
... console.dir(res);
... })
undefined
> [ { level: 'priority', nbBlocks: 1, feePerKB: 62115 }, // pass these feePerKB values into the feePerKb opts for createTxProposal.
  { level: 'normal', nbBlocks: 2, feePerKB: 44026 },
  { level: 'economy', nbBlocks: 6, feePerKB: 29840 },
  { level: 'superEconomy', nbBlocks: 24, feePerKB: 26750 } ]
```

**Comment by dabura667** [comment]
You never want to set `fee` directly, only set `feePerKb` when creating transaction Proposal...

just be careful, as maybe the "priority fee" doubles during the time you are gathering the necessary signatures.... who knows... (with recent events I wouldn't be surprised)

So to answer your question:

1. getUtxos will give you utxos with 0 confirmations just fine.
2. you can get a current fee rate for the bitcoin network using getFeeLevels and always use priority if you would like to chain together unconfirmed.
3. If possible, try to gather up multiple user requests into one transaction by joining multiple outputs into one transaction proposal.

**Comment by igorvlassov** [comment]
Dear @dabura667 ,
Thanks a lot for so great explanation!
Especially about 0 confirmations & getFeeLevels

**Comment by Chibuzo** [comment]
Thanks @igorvlassov and @dabura667 for this thread. I've learnt a lot from it already.

However, is it possible to use `utxo` from different wallet in one transaction when sending to many addresses?
