### ISSUE TITLE
Join wallet from an existing wallet

### ISSUE THREAD

**Issue by carlosfaria94** [bitpay/bitcore-wallet-client#296]
I'm trying to understand some behaviors of API.joinWallet, and I got some questions:
- Why joinWallet return another wallet? What's the used for? If I already have the wallet, why generate new one?
- If I had one wallet that I want to join to new ones, I simply create this wallets and join my wallet with this secret wallet, right?

Thanks.

**Comment by dabura667** [comment]
> Why joinWallet return another wallet? What's the used for? If I already have the wallet, why generate new one?

Let's separate some terms here for a second:

1. credentials = the private key chain (or mnemonic) that your client has in the local wallet file (where you export to)
2. shared wallet = a wallet object on BWS which contains multiple individual wallets. It also contains metadata about the shared wallet along with pointers to each individual wallet will need to query BWS about the shared wallet.
3. individual wallet = a wallet object on BWS which contains references to the public parts of an individual copayer's credentials, if it is a part of a shared wallet, then it also contains the metadata and **shared secrets needed to participate in the shared wallet**.

The "another wallet" is the same wallet you had before, just with extra shared keys added. Your individual wallet (that you save locally) needs to store these shared keys for encrypting messages to BWS when pertaining to your shared wallet.

I believe it is also automatically applied to the client object's credentials as well, so performing a client.export in the callback for joinWallet should be sufficient... but some people wouldn't find that intuitive for the callback methodology, so they are also returning the wallet as an arg of the callback for convenience.

(**correct me if I'm wrong, I might be**)

> If I had one wallet that I want to join to new ones, I simply create this wallets and join my wallet with this secret wallet, right?

I can't really understand what you mean... but if you mean "can I join multiple shared wallets with the same credentials?" the answer is yes... but "can I join multiple shared wallets with the same individual wallet?" the answer is no.

However, it is highly recommended that you use different xprv keys for each wallet you join or create... if you must have one backup, create one wallet with mnemonic, then use bitcore-mnemonic library to convert mnemonic to HDPrivateKey and derive `m/44'/0'/1'` then `m/44'/0'/2'` then `m/44'/0'/3'` to generate the 2nd, 3rd, 4th account of the same mnemonic and use those HDPrivateKeys to export as xprv and use that to initialize credentials with bitcore-wallet-client.

**Comment by carlosfaria94** [comment]
Thanks for your explanation, lots of thing got clear now, really.

Thanks for your recommendation, but if I have this wallets:
```
createWallet("Main", "Bob", 2, 3) // return: mainSecret
createWallet("Backup", "Bob", **1, 1**)
createWallet("TomWallet", "Tom", 1, 1)

joinWallet(mainSecret, "Bob") // associate the Bob Backup wallet to the Main wallet
joinWallet(mainSecret, "Tom") // associate the Tom wallet to the Main wallet of the Bob
```
This process is recommended?

When you say: 

> and derive m/44'/0'/1' then m/44'/0'/2' then m/44'/0'/3' to generate the 2nd, 3rd, 4th account of the same mnemonic and use those HDPrivateKeys to export as xprv and use that to initialize credentials with bitcore-wallet-client. 

This can be done with API.seedFromExtendedPrivateKey, right?

**Comment by dabura667** [comment]
> This process is recommended?

No.

createWallet will create a wallet on BWS that is either Shared wallet or Individual wallet. But if you create a 1 of 1 wallet, it is always a 1 of 1, and can not join a shared wallet.

You would need to do something like (psuedo code)

```javascript
// each client object is an instance of bitcore-wallet-client with their own credentials
// pre-initialized via seedFromExtendedPrivateKey or something else. Note that if you
// run createWallet or joinWallet without any credentials loaded, it will automatically
// generate a new mnemonic credentials for you

// No need to initialize, a random will be made
client1.createWallet("Main", "Bob", 2, 3) // return: mainSecret

var HDKey = client1.credentials.xPrivKey

// initialize clients before joining the shared wallet
client2.seedFromExtendedPrivateKey(HDKey, {account: 1}) // account #2 (start counting from 0)
client3.seedFromExtendedPrivateKey(HDKey, {account: 2}) // account #3 (start counting from 0)

client2.joinWallet(mainSecret, "Bob") // associate the Bob Backup wallet to the Main wallet
client3.joinWallet(mainSecret, "Tom") // associate the Tom wallet to the Main wallet of the Bob
```

**Comment by carlosfaria94** [comment]
Thanks @dabura667 for your help, now Its all more clear!

**Comment by carlosfaria94** [comment]
Thanks @dabura667 for your help, now Its all more clear..

but one more doubt, I already code what you did, and now I got 3 wallets with the same private key, the goal is not to have 3 different keys? Or I missing something?

**Comment by dabura667** [comment]
It will derive the account before generating the actual keys.

I thought the wallet stored m/44'/0'/a' but in actuality it stores m and a as two pieces of data, and generates m/44'/0'/a'/c/k for each key.

You are fine.

**Comment by carlosfaria94** [comment]
@dabura667 I have the Bob  (Main and Backup wallet), but if I want Tom audit the transactions that Bob is doing (full access to the list of incoming and outgoing payments), but Tom is not authorized to spend money of the Bob wallets.

https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki --> Use cases / Audits: N(m/*)

**Comment by dabura667** [comment]
https://github.com/bitpay/bitcore-wallet-client/blob/41635442819ccd9b6d97ac5a7a46869ead7a35f1/lib/api.js#L452

1. Bob makes a wallet.
2. Bob runs: `client.export({noSign: true})` and saves the string to a file.
3. Tom runs `client.import()` with the file from Bob.
4. Tom opens the wallet, then re-exports it and saves to disk.

Now Tom essentially has the exact same wallet as Bob except without the ability to sign.

(However, Tom will have the ability to propose transactions on Bob's behalf, and any co-signers would see his proposals as "from Bob"...)

**Comment by carlosfaria94** [comment]
But if Tom had the same xpriv as Bob do I really need to do import and export?
--
In the sample code you show pervasively, instead of seedFromExtendedPrivateKey I choose seedFromRandomWithMnemonic.
Are the Mnemonic a good option?
And Mnemonic are stored in the credentials file, are they sensitive data, like xpriv?

**Comment by dabura667** [comment]
> But if Tom had the same xpriv as Bob do I really need to do import and export?

If we are talking about my code sample. That is a multi-sig wallet. Tom can already see all the transactions that Bob is doing, because Tom also has to approve them (that is what multi-sig is... multiple approvers)

But in the (very very bad security) example I gave you, since everyone has the same xprv, it's a useless multisig wallet. There is no meaning to having multiple signatures if everyone owns the same key. (Bob could create Tom's wallet by re-creating the wallet with the account number 2 instead of 0.)

I don't understand what you are trying to accomplish, stop talking in abstract "Bob" and "Tom" metaphors and just say what you want to do: ie. "I want to set up a server that can watch my wallet and send an email to my lawyer every time I get money" or something like that.

**Comment by carlosfaria94** [comment]
> If we are talking about my code sample. That is a multi-sig wallet. Tom can already see all the transactions that Bob is doing, because Tom also has to approve them (that is what multi-sig is... multiple approvers)

Yes, I know. So, I will explain: I want a server that audit all the transactions of the users, but the server has only access to one key pair for each user. And a user have 2 wallets/credentials (main and offline backup).

My ideia:

```
// Doing this offline:
client1.createWallet("Main", "UserName", 2, 3) // return: mainSecret

client2. seedFromRandom()
client2.joinWallet(mainSecret, "Backup") // export() and store offline (print), in case the Main is lost.

// On the server (server receive mainSecret form the client):
client3. seedFromRandomWithMnemonic({passphrase, account: 2})
client3.joinWallet(mainSecret, "Server")
```

But I want createWallet() using Mnemonic, so that the user only need to memorize the Mnemonic and the passphrase. So when is login in I use importFromMnemonic().

What you think? Thanks for your patience.

**Comment by dabura667** [comment]
1. createWallet and joinWallet can not be done offline.
2. passphrase is inside your json object alone. That it incorrect.
3. If everyone is using separate keys (seedFromRandomWithMnemonic) then you don't need to touch the "account" value. Leave it at default (0).
4. You can initialize credentials with an xpub only.
5. User should do createWallet to generate their online key and create the wallet, which the server will join using xpub (you should keep the server keys offline too if possible.) or whatever.
6. The user must have some way to create a key offline, and relay only the xpub and the entropy info (if you will derive from xprv or mnemonic) to the online computer to use joinWallet.

Air gapped signing, joining wallets with xpub only and signing for it later are some of the more confusing parts of bwc... so it is very hard to explain over some message like this. You will have to figure it out on your own.

As a hint, I have a PR open to allow for user to sign offline without needing anything but xprv or mnemonic.

https://github.com/bitpay/bitcore-wallet-client/pull/291/files

**Comment by carlosfaria94** [comment]
Thanks for your advices, I will explore this.
