### ISSUE TITLE
Getting error: bwc.ErrorNOT_FOUND in client.sendTxProposal

### ISSUE THREAD

**Issue by ziggamon** [bitpay/bitcore-wallet-client#306]
Hi, 

Today getting errors from client.sendTxProposal, using the bws.bitpay.com bitcore server. 

Error message:
debug: Request._callback (/Code/project/node_modules/bitcore-wallet-client/lib/api.js:781:9)] 'Cannot POST /bws/api/v1/txproposals/\n

Any ideas what this could be?

Version 2.11.0, worked fine until yesterday. Any changes that have been deployed? Copay wallet seems to still work tho...

Thanks,
Sergej

**Comment by isocolsky** [comment]
Hi,
The current bws.bitpay.com service no longer supports `sendTxProposal` method. This method has been replaced by the new flow `createTxProposal` + `publishTxProposal` (which is the approach used by the Copay app). These methods are included in bwc v2.11.0. We are releasing bwc v3.0.0 and updating the documentation. Sorry for the inconvenience.

**Comment by ziggamon** [comment]
Ok, thanks. 

Updated code to use those two functions, now it sometimes works, but oftentimes getting the following Cludflare error:
525: SSL handshake failed

With a full HTML page from Cloudflare about this error.

Any idea what's going on? Copay wallet seems to still work strangely enough...

**Comment by ziggamon** [comment]
Ok, managed to debug that error too. It happens when using a single output transaction. I converted the send to a multiple_outputs with an array of one tx and then it worked.

But SSL error is really not the best error to display, and it'd be great to get some notification about API breaking changes.

**Comment by matiu** [comment]
thanks. We were able to reproduce it. We will fix it soon.

**Comment by chrisrico** [comment]
@matiu, what is the new flow for a 1-of-3 wallet, where in the usual case a program signs and publishes transactions automatically?

I used to do ```sendTxProposal(); signTxProposal(); broadcastTxProposal()```.

**Comment by isocolsky** [comment]
`sendTxProposal` is now two methods: `createTxProposal` which selects inputs (but does not lock them) and `publishTxProposal` which makes the proposal available to other copayers and ready to be signed.

**Comment by chrisrico** [comment]
So the new full flow is create, publish, sign, broadcast?

**Comment by isocolsky** [comment]
yes, that is correct.

**Comment by got3nks** [comment]
I'm having issues with the new sendTxProposal function

```
var opts = {outputs: [{toAddress: args[0], amount: Math.round(args[1] * 100000000), message: args[2]}], message: args[2]};

wallet.createTxProposal(opts, function(err, proposal) {
...
}
```

**Error: BADREQUEST: Required argument missing**

What am I missing?

**Comment by isocolsky** [comment]
If you are using BWC < v3.2.0 then you should also be passing `feePerKb` argument.

**Comment by got3nks** [comment]
I have updated to v4.0.0 but I still get this error.

**Comment by isocolsky** [comment]
Have you tried adding `feePerKb`? I think that will solve the issue. I now see you are using your own BWS so that may need to be upgraded as well.

**Comment by got3nks** [comment]
I'd rather let the client choose an appropriate feePerKb value (I guess based on the Bitcoin Network transactions backlog)

**Comment by isocolsky** [comment]
In BWC > 3.2.0 + BWS v1.11.0 you can specify `FeeLevel` to be one of 'priority', 'normal', 'economy' and 'superEconomy'. The default value is 'normal'. These values are computed by BWS using the `getFeeLevels` method (which serves the `v2/feeLevel` API endpoint).

**Comment by got3nks** [comment]
I've solved it by adding the `feePerKb` argument (calculated through the ` getFeeLevels` function). The documentation should be updated though, it currently shows `feePerKb` as **optional**.

**Comment by isocolsky** [comment]
`feePerKb` is currently optional. Check out this test from BWC: https://github.com/bitpay/bitcore-wallet-client/blob/master/test/client.js#L1894 . Fees are not specified yet the tx is successfully created.
