### ISSUE TITLE
Have some forum that lets newer users post questions about the usage of wallet client?

### ISSUE THREAD

**Issue by alvaro-paco** [bitpay/bitcore-wallet-client#312]
I'm a new user and I have some question about the bitore-wallet-client usage but i think this Issue section doesn't is the place to solve that questions. I've been searching on google and Stackoverflow but I not found any forum. So, please, have any place that i can ask for a senior user about my questions?

**Comment by carlosfaria94** [comment]
You can find help here: https://forum.bitcore.io/c/bitcore-wallet




On Wed, Aug 17, 2016 at 5:06 PM +0100, "Alvaro Paçó" <notifications@github.com> wrote:












I'm a new user and I have some question about the bitore-wallet-client usage but i think this Issue section doesn't is the place to solve that questions. I've been searching on google and Stackoverflow but I not found any forum. So, please, have any place that i can ask for a senior user about my questions?
