### ISSUE TITLE
ErrorNOT_AUTHORIZED: Copayer not found Importing wallet

### ISSUE THREAD

**Issue by carlosfaria94** [bitpay/bitcore-wallet-client#317]
Hi,

I'm trying to importFromMnemonic but I'm getting `bwc.ErrorNOT_AUTHORIZED: Copayer not found`

So, I have the mnemonic words and passphrase, from one wallet in a 2-3 HD, and I want to get credentials from this wallet. From the mnemonic wallet, ex:

```
    "words":"flash engage prepare hello dash involve again differ dentist any rate hamster",
    "passphrase":"123"
```

What I'm doing:

```
let bwClient = new Client(BW_CLIENT_OPTS);
bwClient.importFromMnemonic(data.words, {'network': 'testnet', passphrase}, (err, wallet) => {
      if (err) return cb(err);
      cb(null, { 'Wallet imported from Mnemonic': bwClient.export() });
    });
```

BWS cannot find the copayer, because I'm not specifying the copayer name, but I know it.

Why not add in all API.import*() the option to insert the copayerName and put here:
https://github.com/bitpay/bitcore-wallet-client/blob/master/lib/api.js#L516 : `self.addAccess({name: opts.copayerName}, (err) => {});`

**Comment by carlosfaria94** [comment]
Sorry, problem solved. Typo.

**Comment by SoftProgramLX** [comment]
I encountered the same problem, how to solve it, thank you!
