### ISSUE TITLE
Why needed to set credentials to getFiatRate?

### ISSUE THREAD

**Issue by carlosfaria94** [bitpay/bitcore-wallet-client#364]
At the moment it is required to set credentials to get fiat rate (https://github.com/bitpay/bitcore-wallet-client/blob/master/lib/api.js#L2356) this is truly needed?

Thanks!

**Comment by isocolsky** [comment]
Good point. I don't think it's needed but both BWS & BWC need to be changed.

**Comment by carlosfaria94** [comment]
In BWS I do not see any check for credentials (https://github.com/bitpay/bitcore-wallet-service/blob/master/lib/server.js#L3040-L3057) I am missing something? The requests are checked in another layer?

In BWC if credentials are not set, they simply pass this condition: https://github.com/bitpay/bitcore-wallet-client/blob/master/lib/api.js#L762 and proceed with the request, without the signature.

I have not tested it yet. But I am missing something?

Thanks!

**Comment by isocolsky** [comment]
Check out this line https://github.com/bitpay/bitcore-wallet-service/blob/master/lib/expressapp.js#L653

the method `getServerWithAuth()` requires credentials to be set.
Instead, we should change it to `getServer()` like in this line: https://github.com/bitpay/bitcore-wallet-service/blob/master/lib/expressapp.js#L401
