### ISSUE TITLE
Unable to Connect to Bitcore-wallet-service from Bitcore-wallet-client

### ISSUE THREAD

**Issue by Chibuzo** [bitpay/bitcore-wallet-client#375]
My bitcore-wallet-service is running well, however, when I try to connect from bitcore-wallet-client I get the following error:

`error:  { [bwc.ErrorCONNECTION_ERROR: Wallet service connection error.]
  message: 'Wallet service connection error.',
  stack: 'Wallet service connection error.\nError\n    at Error.NodeError (/home/chibuzo/cpbitcoin/node_modules/bitcore-wallet-client/lib/errors/index.js:20:41)\n    at /home/chibuzo/cpbitcoin/node_modules/bitcore-wallet-client/lib/api.js:799:17\n    at Request.callback (/home/chibuzo/cpbitcoin/node_modules/bitcore-wallet-client/node_modules/superagent/lib/node/index.js:688:3)\n    at ClientRequest.<anonymous> (/home/chibuzo/cpbitcoin/node_modules/bitcore-wallet-client/node_modules/superagent/lib/node/index.js:615:10)\n    at ClientRequest.g (events.js:180:16)\n    at ClientRequest.emit (events.js:95:17)\n    at Socket.socketErrorListener (http.js:1547:9)\n    at Socket.emit (events.js:95:17)\n    at net.js:440:14\n    at process._tickDomainCallback (node.js:463:13)' }
`

My bitcore-wallet-client is on a different node app, but on the same server with the wallet service.

Please I need assistance.

Thanks

**Comment by dabura667** [comment]
What are you passing bwc as your bws api endpoint?

**Comment by Chibuzo** [comment]
var BWS_INSTANCE_URL = 'http://localhost:3232/bws/api'

**Comment by dabura667** [comment]
Try this command on your terminal. Tell me what it gives you.

curl http://localhost:3232/bws/api/v2/feelevels

**Comment by Chibuzo** [comment]
curl: (7) Failed to connect to localhost port 3232: Connection refused

Meanwhile I discovered that my disk is full and bitcore-node couldn't run because of that. Could that be the cause?

**Comment by xelawafs** [comment]
@dabura667 I have the same issue. This is what I get when I run

`curl http://localhost:3232/bws/api/v2/feelevels`

`[{"level":"urgent","feePerKb":768269,"nbBlocks":2},{"level":"priority","feePerKb":512179,"nbBlocks":2},{"level":"normal","feePerKb":512179,"nbBlocks":3},{"level":"economy","feePerKb":423583,"nbBlocks":6},{"level":"superEconomy","feePerKb":391761,"nbBlocks":24}]`

**Comment by leoloco** [comment]
The problem comes from the similink, I had the same problem, just run : 
`wallet -h http://localhost:3232/bws/api <your comman>`
instead
