### ISSUE TITLE
Unable to connect with 3232

### ISSUE THREAD

**Issue by Lalitpatadiya12** [bitpay/bitcore-wallet-client#385]
Unable to connect

Firefox can’t establish a connection to the server at localhost:3232.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by matiu** [comment]
Bitcore Wallet Client is a  client library, you need to run bitcore-wallet-service to connect to it.

**Comment by Lalitpatadiya12** [comment]
@matiu  3232 is the bitcore wallet client library port number ..? and one more thing is i have already installed bitcore wallet service into my system.
Can you please guide me how to run bitcoin-wallet-service ..?
