### ISSUE TITLE
How to Spend from more than one UTXO

### ISSUE THREAD

**Issue by Chibuzo** [bitpay/bitcore-wallet-client#386]
I need to transfer BTC from different wallets to one address. I understand that for a transaction, the `input` is an array. So I assume I can use more than one `UTXO` as input. Is that correct?

If that's correct, is there a way I could specify the amount of Satoshi I want to spend from each of the UTXO?

**Comment by jeshan** [comment]
any reason why you want to specify the inputs? why don't you let bitcore choose them for you?

**Comment by Chibuzo** [comment]
I want to spend from different wallet.

**Comment by jeshan** [comment]
i don't think you can spend bitcoins from different wallets as part of the same transaction.

**Comment by dabura667** [comment]
> is there a way I could specify the amount of Satoshi I want to spend from each of the UTXO?

In Bitcoin, you must spend every input completely. There is no such thing as partially spending an input.

You can adjust where the leftover funds end up by including extra outputs (such as change outputs)
