### ISSUE TITLE
How to generate multiple address using bitcore wallet service

### ISSUE THREAD

**Issue by Lalitpatadiya12** [bitpay/bitcore-wallet-client#388]
I am using bitcore wallet service. which gives the features like create wallet, wallet balance,generate proposal...etc, here is the link of 

https://github.com/bitpay/bitcore-wallet-client which i have follow.

But if i want to generate multiple address using bitcore wallet service is it possible. because i can not found any details from the entire documents.

**Comment by jeshan** [comment]
didn't API.createAddress work?
https://github.com/bitpay/bitcore-wallet-client#apicreateaddressopts-optsignoremaxgap-cb

**Comment by matiu** [comment]
Yes, use createAddress.

Take a look of bitcore-wallet-client also.

**Comment by Lalitpatadiya12** [comment]
@matiu and @jeshan   I can not found any request parameter like privateKey or wallet Id, so how we identify or know newly generated address is connected with whom..?

**Comment by jeshan** [comment]
you need a wallet to create the address so isn't that sufficient to know that this is the wallet from which  the address was generated?

**Comment by Lalitpatadiya12** [comment]
@jeshan  If i want to create address using @matiu suggested createAddress, but i can not find any parameter like wallet id or privatekey something which will relate that address.
