### ISSUE TITLE
Challenge Sending Bitcoin to more than address

### ISSUE THREAD

**Issue by Chibuzo** [bitpay/bitcore-wallet-client#390]
I'm trying to send bitcoin to more than one address, but it only sends to first address. Below is the structure of my input.

`var outputs = [`
     ` {`
                       ` toAddress: send_addr,`
                       ` amount: amount * 100000000`
                  `  },`
                   ` {`
                        `toAddress: 'n2ATSR21w5KPBju1TakFsvLAVspxqqJdAc',`
                        `amount: 0.0001 * 100000000`
                   ` }`
               ` ];`
               ` var opts = {`
                    `outputs: outputs,`
                   ` message: msg,`
                   ` feePerKb: 50000`
               ` };`

Please how do I do this while specifying the amount to send to each address.

**Comment by jeshan** [comment]
show us how you called the API

**Comment by Chibuzo** [comment]
Like this

`client.createTxProposal( opts, function (err, txp) { 
     // the rest of the code... });`

Note: the code works but sends to the first address only.

**Comment by jeshan** [comment]
looks good to me, so your issue is surely somewhere else.
