### ISSUE TITLE
importFromMnemonic not work for new mnemonic wallet.

### ISSUE THREAD

**Issue by Ray-cheng** [bitpay/bitcore-wallet-client#427]
I've a new mnemonic wallet  when I call importFromMnemonic to import it into copay, it's failed,the err message is : Copayer not found, I don't know the reason, can somebody tell me?

**Comment by matiu** [comment]
This is probably becausea the wallet is not yet created on BWS.

If the wallet does not exist on the server, you need to:

1. call `seedFromRandomWithMnemonic`
2. then call `createWallet`

Eq:
```

walletClient.seedFromMnemonic(opts.mnemonic, {

```
var client = new Client({
  baseUrl: BWS_INSTANCE_URL
});

client.seedFromMnemonic(<words>);

client.createWallet(...
```

the README for more options.
