### ISSUE TITLE
Unable to broadcast transaction - what should I do about it?

### ISSUE THREAD

**Issue by offerm** [bitpay/bitcore-wallet-client#80]
C:\workspace_sts\bitcore-wallet\bin>node wallet status
* Wallet BNHP [testnet]: 2-of-4 complete
* Copayers: CryptoBox, Offer Web, Offer mobile, tomer
* Balance 1,999,650 bit (Locked: 0 bit)
* TX Proposals:
        3955 ["" by CryptoBox] 1,000,000 bit => mnAPzVRFvqdS7EcouuGv5q5sC9Z6ZhLL
Y4
                Actions:  Offer mobile √. Offer Web √
                Ready to broadcast

C:\workspace_sts\bitcore-wallet\bin>node wallet broadcast 3955
[error] [object Object]
{ code: 'ERROR', error: 'Generic error  (code -25)' }

**Comment by offerm** [comment]
Anyone?
The transaction is signed by 2 of 4 but I can't broadcast it.
Must be a problem on the backend server.
Anyway to remove it?

**Comment by matiu** [comment]
Are you using the public Bitpay's BWS instance?

This is a testnet wallet, right?  could you try again to list the transactions and broadcast the pending one?

**Comment by offerm** [comment]
Yes. I'm useing the public BWS.
It is a testnet wallet.

not sure what you mean by "list the transactions".

I tried to broadcast the signed transaction and got the same error.

I can send you the wallet file if you like.

Offer

**Comment by matiu** [comment]
The error you are receiving is: (-25) directly from bitcoind:
https://github.com/bitcoin/bitcoin/blob/master/src/rpcprotocol.h#L53

It seems that the unspent for the transaction are already spent:

Inputs TxId:
9cfa0b0d4abe94e8218086b26cd259eacd956023bef4fd83be4e2989622282cd
2b3450f9c4c94ed7dbeeec4b9a0fe079a55e5c3ebe7787ec9eaa008a909e73db
(already spent)

see for example:
https://test-insight.bitpay.com/tx/9cfa0b0d4abe94e8218086b26cd259eacd956023bef4fd83be4e2989622282cd

The transaction that spent them is: (8fdbda891dd8c3ceee27105b20b7b2fe287f087b3717c1abdc8be0fa828980f6)
https://test-insight.bitpay.com/tx/8fdbda891dd8c3ceee27105b20b7b2fe287f087b3717c1abdc8be0fa828980f6
[toAddress: muNcFv7uEjr5eEpWezAEMDwvtAQz8LfM6j]

Created 4 minutes before the one that is stocked.

We are investigating the issue. We have migrate the BWS server a couple of times last month to add redundancy, and maybe some issue was created there. Could you provide some background how this transactions we created?

Thanks.

**Comment by offerm** [comment]
Amy way to remove this transaction?

Might be that I created 2 transactions A and B and signed B before A.
I will try to reproduce later and let you know,

Offer

**Comment by matiu** [comment]
yes, the transaction we deleted since the input are spent. We are checking what happened. Thanks for the report. Closing this one now. Will keep it updated.
